#!/usr/bin/env python3

"""
GOParsimony Visualization Script
--------------------------------
Generates visual representations of Gene Ontology 
enrichment/depletion data.

Copyright 2026. Paul Martin Harrison 

License: 3-clause BSD licence 

Expected Inputs:
    --results    : Path to the Enrichment_Results.tsv generated by GOParsimony.c
    --edges      : Path to the Precedence_Edges.tsv generated by GOParsimony.c
    --sig_prots  : Path to the Significantly_Annotated_List.tsv

Optional Inputs:
    --out        : Prefix string for all generated PDF files
    --highlight  : Text file containing GO terms to highlight with green borders
    --max_prec   : Integer (default: 5). The maximum precedence level threshold 
                   to include in concise DAGs and clustering heatmaps.

To run and get help: 
  python3 precedence-graphs.py -h 
  OR 
  python3 precedence-graphs.py --help 
"""

import os
import argparse
import html
import textwrap
import pandas as pd
import graphviz
import numpy as np
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
import scipy.spatial.distance as ssd
import seaborn as sns
from matplotlib.colors import ListedColormap
from matplotlib.lines import Line2D
import matplotlib.patches as mpatches
from matplotlib.backends.backend_pdf import PdfPages

# Force Python to look in Mac's default Homebrew installation folders for 'dot'
os.environ["PATH"] += os.pathsep + '/opt/homebrew/bin' + os.pathsep + '/usr/local/bin'

def generate_graphs(results_file, edges_file, out_file, highlight_file, sig_prots_file, max_prec):
    # Establish dynamic file prefix
    prefix = f"{out_file}." if out_file else ""
    
    print("=======================================================================")
    print(" NOTE: This script draws Structural Precedence DAGs, Sorted Tables,")
    print(f" 2D Heatmaps, Bar Charts, AND Overlap Venn Diagrams (Prec <= {max_prec}).")
    print("=======================================================================\n")
    print(f"Loading data from '{results_file}' and '{edges_file}'...")
    
    # -------------------------------------------------------------------------
    # 1. LOAD DATA & HIGHLIGHTS
    # -------------------------------------------------------------------------
    highlighted_terms = set()
    if highlight_file:
        try:
            with open(highlight_file, 'r') as f:
                for line in f:
                    t = line.strip()
                    if t: highlighted_terms.add(t)
            print(f"Loaded {len(highlighted_terms)} terms to highlight.")
        except Exception as e:
            print(f"Warning: Could not read highlight file: {e}")

    try:
        results_df = pd.read_csv(results_file, sep="\t")
        try:
            edges_df = pd.read_csv(edges_file, sep="\t")
            if 'EdgeStyle' not in edges_df.columns:
                edges_df['EdgeStyle'] = 'solid'
        except pd.errors.EmptyDataError:
            edges_df = pd.DataFrame(columns=['Parent', 'Child', 'ClusterID', 'Namespace', 'Enr/Dep', 'EdgeStyle'])
    except FileNotFoundError as e:
        print(f"Error: {e}. Please ensure you ran the C program and the paths are correct.")
        return
        
    if 'Is_Slim' not in results_df.columns:
        results_df['Is_Slim'] = 'No'
        
    has_reg_cols = 'Reg_Prec' in results_df.columns

    results_df['ClusterID'] = pd.to_numeric(results_df['ClusterID'], errors='coerce').fillna(0)
    
    # Explicitly copy the dataframe to avoid pandas SettingWithCopyWarning
    sig_results = results_df[results_df['ClusterID'] > 0].copy()
    
    if len(sig_results) == 0:
        print("No significant clusters found to draw.")
        return

    # Calculate numeric Precedence globally so it can be used for filtering tables and concise graphs
    sig_results['Prec_Clean'] = sig_results['Prec'].astype(str).str.replace('*', '', regex=False).str.strip()
    sig_results['Prec_Num'] = pd.to_numeric(sig_results['Prec_Clean'], errors='coerce').fillna(99).astype(int)

    # Extract Namespace mapping for later use in the 2D Heatmap
    term_to_ns = {}
    if 'Namespace' in results_df.columns:
        for _, row in results_df.iterrows():
            term_to_ns[row['GOTerm']] = str(row['Namespace']).strip()

    color_map = {
        1: "#4292c6",
        2: "#6baed6",
        3: "#9ecae1",
        4: "#c6dbef",
        5: "#dbe9f6",
        6: "#eff3f9",
        7: "#f7fbff"
    }

    # -------------------------------------------------------------------------
    # 2. PAGE 1: ALL PRECEDENCE DAGs (Complete Graph)
    # -------------------------------------------------------------------------
    dot = graphviz.Digraph(name='All_Precedence_Graphs')
    dot.attr(rankdir='TB', nodesep='0.4', ranksep='0.6', compound='true') 
    dot.attr(label='PRECEDENCE GRAPHS\n', labelloc='t', fontsize='24', fontname='Arial-Bold')

    for res_type in ['Enr', 'Dep']:
        sub_df = sig_results[sig_results['Enr/Dep'] == res_type]
        sub_edges = edges_df[edges_df['Enr/Dep'] == res_type]
        
        if len(sub_df) == 0: continue
            
        with dot.subgraph(name=f'cluster_{res_type}') as c:
            c.attr(label="Enrichment" if res_type == "Enr" else "Depletion", fontsize='26', fontname='Arial-Bold', penwidth='2', style='dashed', color='gray')
            
            # Draw ALL nodes directly (No ClusterID grouping)
            for _, row in sub_df.iterrows():
                go_id = str(row['GOTerm']) 
                raw_name = str(row['Description']) 
                escaped_name = html.escape(raw_name)
                wrapped_name = "<BR/>".join(textwrap.wrap(escaped_name, width=25))
                
                prec_str = str(row['Prec']).strip()
                prec_val = int(row['Prec_Num'])
                p_val = float(row['P_Value'])
                is_slim = str(row['Is_Slim']).strip().lower() == 'yes'
                is_highlighted = go_id in highlighted_terms
                ns = html.escape(str(row['Namespace'])) 
                
                safe_id = go_id.replace(":", "_") + "_" + res_type
                fillcolor = color_map.get(prec_val, "white")
                
                if prec_val == 1:
                    inner_html = f'''<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="1">
                    <TR><TD ALIGN="CENTER"><B>{go_id} ({prec_str})</B></TD></TR>
                    <TR><TD ALIGN="CENTER"><B>{wrapped_name}</B></TD></TR>
                    <TR><TD ALIGN="CENTER"><B>{p_val:.2e}</B></TD></TR>
                    <TR><TD ALIGN="RIGHT"><FONT POINT-SIZE="10"><B>{ns}</B></FONT></TD></TR>
                    </TABLE>'''
                else:
                    inner_html = f'''<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="1">
                    <TR><TD ALIGN="CENTER">{go_id} ({prec_str})</TD></TR>
                    <TR><TD ALIGN="CENTER">{wrapped_name}</TD></TR>
                    <TR><TD ALIGN="CENTER">{p_val:.2e}</TD></TR>
                    <TR><TD ALIGN="RIGHT"><FONT POINT-SIZE="10"><B>{ns}</B></FONT></TD></TR>
                    </TABLE>'''
                
                if is_highlighted and is_slim:
                    label = f'''<<TABLE BORDER="4" COLOR="green" CELLBORDER="0" CELLSPACING="3" CELLPADDING="0" BGCOLOR="white">
                    <TR><TD BORDER="4" COLOR="magenta" BGCOLOR="{fillcolor}" CELLPADDING="6">
                    {inner_html}
                    </TD></TR></TABLE>>'''
                    c.node(safe_id, label=label, shape="plaintext", fontname="Arial")
                else:
                    if is_highlighted: border_color, penwidth = "green", "4.0"
                    elif is_slim: border_color, penwidth = "magenta", "4.0"
                    else: border_color, penwidth = "black", ("3.0" if prec_val == 1 else "1.0")
                        
                    c.node(safe_id, label=f"<{inner_html}>", style="filled", fillcolor=fillcolor, color=border_color, shape="box", fontname="Arial", penwidth=penwidth)

            # Draw ALL edges
            for _, row in sub_edges.iterrows():
                safe_parent = str(row['Parent']).replace(":", "_") + "_" + res_type
                safe_child = str(row['Child']).replace(":", "_") + "_" + res_type
                e_style = str(row.get('EdgeStyle', 'solid'))
                c.edge(safe_parent, safe_child, style=e_style)

    dag_out = f"{prefix}Precedence-Graphs"
    dot.render(dag_out, format='pdf', cleanup=True)
    print(f" -> Success! Generated '{dag_out}.pdf'")

    # -------------------------------------------------------------------------
    # 3. PAGE 1B: CONCISE PRECEDENCE DAGs (Filtered to max_prec + skip edges)
    # -------------------------------------------------------------------------
    dot_concise = graphviz.Digraph(name='Concise_Precedence_Graphs')
    dot_concise.attr(rankdir='TB', nodesep='0.4', ranksep='0.6', compound='true') 
    dot_concise.attr(label=f'CONCISE PRECEDENCE GRAPHS (Prec <= {max_prec})\n', labelloc='t', fontsize='24', fontname='Arial-Bold')

    for res_type in ['Enr', 'Dep']:
        sub_df = sig_results[sig_results['Enr/Dep'] == res_type]
        sub_edges = edges_df[edges_df['Enr/Dep'] == res_type]
        
        if len(sub_df) == 0: continue
            
        with dot_concise.subgraph(name=f'cluster_{res_type}') as c:
            c.attr(label="Enrichment" if res_type == "Enr" else "Depletion", fontsize='26', fontname='Arial-Bold', penwidth='2', style='dashed', color='gray')
            
            # Determine the kept nodes based on max_prec globally for this Enr/Dep type
            kept_nodes_df = sub_df[sub_df['Prec_Num'] <= max_prec]
            kept_go_terms = set(kept_nodes_df['GOTerm'].astype(str))
            
            # Draw all kept nodes
            for _, row in kept_nodes_df.iterrows():
                go_id = str(row['GOTerm']) 
                raw_name = str(row['Description']) 
                escaped_name = html.escape(raw_name)
                wrapped_name = "<BR/>".join(textwrap.wrap(escaped_name, width=25))
                prec_str = str(row['Prec']).strip()
                prec_val = int(row['Prec_Num'])
                p_val = float(row['P_Value'])
                is_slim = str(row['Is_Slim']).strip().lower() == 'yes'
                is_highlighted = go_id in highlighted_terms
                ns = html.escape(str(row['Namespace'])) 
                
                safe_id = go_id.replace(":", "_") + "_" + res_type
                fillcolor = color_map.get(prec_val, "white")
                
                if prec_val == 1:
                    inner_html = f'''<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="1">
                    <TR><TD ALIGN="CENTER"><B>{go_id} ({prec_str})</B></TD></TR>
                    <TR><TD ALIGN="CENTER"><B>{wrapped_name}</B></TD></TR>
                    <TR><TD ALIGN="CENTER"><B>{p_val:.2e}</B></TD></TR>
                    <TR><TD ALIGN="RIGHT"><FONT POINT-SIZE="10"><B>{ns}</B></FONT></TD></TR>
                    </TABLE>'''
                else:
                    inner_html = f'''<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="1">
                    <TR><TD ALIGN="CENTER">{go_id} ({prec_str})</TD></TR>
                    <TR><TD ALIGN="CENTER">{wrapped_name}</TD></TR>
                    <TR><TD ALIGN="CENTER">{p_val:.2e}</TD></TR>
                    <TR><TD ALIGN="RIGHT"><FONT POINT-SIZE="10"><B>{ns}</B></FONT></TD></TR>
                    </TABLE>'''
                
                if is_highlighted and is_slim:
                    label = f'''<<TABLE BORDER="4" COLOR="green" CELLBORDER="0" CELLSPACING="3" CELLPADDING="0" BGCOLOR="white">
                    <TR><TD BORDER="4" COLOR="magenta" BGCOLOR="{fillcolor}" CELLPADDING="6">
                    {inner_html}
                    </TD></TR></TABLE>>'''
                    c.node(safe_id, label=label, shape="plaintext", fontname="Arial")
                else:
                    if is_highlighted: border_color, penwidth = "green", "4.0"
                    elif is_slim: border_color, penwidth = "magenta", "4.0"
                    else: border_color, penwidth = "black", ("3.0" if prec_val == 1 else "1.0")
                        
                    c.node(safe_id, label=f"<{inner_html}>", style="filled", fillcolor=fillcolor, color=border_color, shape="box", fontname="Arial", penwidth=penwidth)

            # Build adjacency matrix globally for all sub_edges in this network
            adj = {}
            orig_styles = {}
            for _, row in sub_edges.iterrows():
                p = str(row['Parent'])
                ch = str(row['Child'])
                if p not in adj: adj[p] = []
                adj[p].append(ch)
                orig_styles[(p, ch)] = str(row.get('EdgeStyle', 'solid'))

            # Calculate concise "Skip" Edges via BFS globally
            for u in kept_go_terms:
                queue = [(child, 1, orig_styles.get((u, child), 'solid')) for child in adj.get(u, [])]
                visited = set()
                
                while queue:
                    curr, dist, style = queue.pop(0)
                    if curr in visited:
                        continue
                    visited.add(curr)
                    
                    if curr in kept_go_terms:
                        final_style = style if dist == 1 else 'dotted'
                        safe_u = u.replace(":", "_") + "_" + res_type
                        safe_curr = curr.replace(":", "_") + "_" + res_type
                        c.edge(safe_u, safe_curr, style=final_style)
                    else:
                        for child in adj.get(curr, []):
                            queue.append((child, dist + 1, style))

    concise_out = f"{prefix}Concise_Precedence_Graphs"
    dot_concise.render(concise_out, format='pdf', cleanup=True)
    print(f" -> Success! Generated '{concise_out}.pdf'")

    # -------------------------------------------------------------------------
    # 4. PAGE 2: SORTED PRECEDENCE TABLE (Filtered to max_prec)
    # -------------------------------------------------------------------------
    dot_table = graphviz.Digraph(name='Precedence_Table')
    dot_table.attr(rankdir='TB')
    dot_table.attr(label=f'GOTERM TABLE (Prec <= {max_prec})\n', labelloc='t', fontsize='24', fontname='Arial-Bold')

    # Filter table to only show nodes where Prec <= max_prec
    sorted_df = sig_results[sig_results['Prec_Num'] <= max_prec].sort_values(by='P_Value', ascending=True)
    html_table = ['<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="6">']
    
    if has_reg_cols:
        html_table.append('<TR><TD BGCOLOR="lightgray"><B>Namespace</B></TD><TD BGCOLOR="lightgray"><B>P-Value</B></TD><TD BGCOLOR="lightgray"><B>Enr/Dep</B></TD><TD BGCOLOR="lightgray"><B>Prec</B></TD><TD BGCOLOR="lightgray"><B>Reg_Prec</B></TD><TD BGCOLOR="lightgray"><B>Reg_ClstID</B></TD><TD BGCOLOR="lightgray"><B>Slim</B></TD><TD BGCOLOR="lightgray"><B>GOTerm</B></TD><TD BGCOLOR="lightgray"><B>Description</B></TD></TR>')
    else:
        html_table.append('<TR><TD BGCOLOR="lightgray"><B>Namespace</B></TD><TD BGCOLOR="lightgray"><B>P-Value</B></TD><TD BGCOLOR="lightgray"><B>Enr/Dep</B></TD><TD BGCOLOR="lightgray"><B>Prec</B></TD><TD BGCOLOR="lightgray"><B>Slim</B></TD><TD BGCOLOR="lightgray"><B>GOTerm</B></TD><TD BGCOLOR="lightgray"><B>Description</B></TD></TR>')

    for _, row in sorted_df.iterrows():
        raw_go_id = str(row['GOTerm'])
        t_go_id = html.escape(raw_go_id)
        t_name_wrapped = "<BR/>".join(textwrap.wrap(html.escape(str(row['Description'])), width=50)) 
        t_ns = html.escape(str(row['Namespace']))
        t_pval = f"{float(row['P_Value']):.2e}"
        t_type = html.escape(str(row['Enr/Dep']))
        t_slim_val = html.escape(str(row['Is_Slim']))
        
        prec_raw = str(row['Prec']).strip()
        prec_val = int(row['Prec_Num'])
        t_prec_str = prec_raw
            
        bg_color = color_map.get(prec_val, "white")
        is_highlighted = raw_go_id in highlighted_terms
        is_slim = t_slim_val.lower() == 'yes'
        
        if is_highlighted and is_slim:
            td_border, td_color, text_color = "3", "green", "magenta"
        elif is_highlighted:
            td_border, td_color, text_color = "3", "green", "black"
        elif is_slim:
            td_border, td_color, text_color = "1", "black", "magenta"
        else:
            td_border, td_color, text_color = "1", "black", "black"
        
        if is_slim:
            t_ns = f'<FONT COLOR="{text_color}">{t_ns}</FONT>'
            t_pval = f'<FONT COLOR="{text_color}">{t_pval}</FONT>'
            t_type = f'<FONT COLOR="{text_color}">{t_type}</FONT>'
            t_prec_str = f'<FONT COLOR="{text_color}">{t_prec_str}</FONT>'
            t_slim_val = f'<FONT COLOR="{text_color}">{t_slim_val}</FONT>'
            t_go_id = f'<FONT COLOR="{text_color}">{t_go_id}</FONT>'
            t_name_wrapped = f'<FONT COLOR="{text_color}">{t_name_wrapped}</FONT>'
        
        if has_reg_cols:
            t_reg_prec = html.escape(str(row['Reg_Prec']))
            t_reg_clst = html.escape(str(row['Reg_ClstID']))
            if is_slim:
                t_reg_prec = f'<FONT COLOR="{text_color}">{t_reg_prec}</FONT>'
                t_reg_clst = f'<FONT COLOR="{text_color}">{t_reg_clst}</FONT>'
                
            html_table.append(f'<TR><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_ns}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_pval}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_type}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_prec_str}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_reg_prec}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_reg_clst}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_slim_val}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_go_id}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_name_wrapped}</TD></TR>')
        else:
            html_table.append(f'<TR><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_ns}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_pval}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_type}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_prec_str}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_slim_val}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_go_id}</TD><TD BGCOLOR="{bg_color}" BORDER="{td_border}" COLOR="{td_color}">{t_name_wrapped}</TD></TR>')

    html_table.append('</TABLE>')
    dot_table.node('table_node', label='<' + "".join(html_table) + '>', shape='plaintext', fontname='Arial')

    table_out = f"{prefix}GOTerm-table"
    dot_table.render(table_out, format='pdf', cleanup=True)
    print(f" -> Success! Generated '{table_out}.pdf'")

    # -------------------------------------------------------------------------
    # 5. 2D CLUSTERGRAM / HEATMAP (Seaborn Jaccard Clustering + Prec Colors)
    # -------------------------------------------------------------------------
    if not sig_prots_file:
        if "Enrichment_Results" in results_file:
            sig_prots_file = results_file.replace("Enrichment_Results", "Significantly_Annotated_List")
        else:
            sig_prots_file = "Significantly_Annotated_List.tsv"

    sp_df_filtered = pd.DataFrame() 
    
    if os.path.exists(sig_prots_file):
        print(f"Generating 2D Clustered Heatmap from '{sig_prots_file}'...")
        try:
            sp_df = pd.read_csv(sig_prots_file, sep="\t")
            
            sp_df['Prec_Clean'] = sp_df['Prec'].astype(str).str.replace('*', '', regex=False).str.strip()
            sp_df['Prec_Num'] = pd.to_numeric(sp_df['Prec_Clean'], errors='coerce').fillna(99).astype(int)
            sp_df_filtered = sp_df[sp_df['Prec_Num'] <= max_prec].copy()
            
            if len(sp_df_filtered) > 1:
                sp_df_filtered['GOTerm_Desc'] = sp_df_filtered['GOTerm'] + " - " + sp_df_filtered['Description']
                
                binary_matrix = pd.crosstab(sp_df_filtered['Protein_ID'], sp_df_filtered['GOTerm_Desc']) > 0
                
                row_dists = ssd.pdist(binary_matrix, metric='jaccard')
                row_linkage = sch.linkage(row_dists, method='average')
                col_dists = ssd.pdist(binary_matrix.T, metric='jaccard')
                col_linkage = sch.linkage(col_dists, method='average')
                
                prec_matrix = sp_df_filtered.pivot_table(
                    index='Protein_ID', 
                    columns='GOTerm_Desc', 
                    values='Prec_Num', 
                    aggfunc='min'
                ).fillna(0).clip(upper=7) 
                
                prec_matrix = prec_matrix.reindex(index=binary_matrix.index, columns=binary_matrix.columns)
                
                annot_matrix = prec_matrix.astype(int).astype(str)
                annot_matrix[prec_matrix == 0] = ""
                
                width = max(12, len(prec_matrix.columns) * 0.35)
                height = max(8, len(prec_matrix.index) * 0.3)
                
                custom_cmap = ListedColormap([
                    '#ffffff', '#4292c6', '#6baed6', '#9ecae1', 
                    '#c6dbef', '#dbe9f6', '#eff3f9', '#f7fbff'
                ])
                
                cg = sns.clustermap(
                    prec_matrix,
                    row_linkage=row_linkage,
                    col_linkage=col_linkage,
                    cmap=custom_cmap,
                    vmin=0, vmax=7,
                    cbar_pos=None,          
                    linewidths=0.5,         
                    linecolor='lightgray',
                    figsize=(width, height),
                    dendrogram_ratio=(0.2, 0.2), 
                    tree_kws={"linewidth": 3.0},
                    annot=annot_matrix,      
                    fmt="",                  
                    annot_kws={"size": 10, "weight": "bold"}
                )
                
                # Triple thickness for abutting dendrogram lines
                for coll in cg.ax_row_dendrogram.collections:
                    widths = [4.5 if np.any(np.isclose(p.vertices[:, 0], 0, atol=1e-3)) else 3.0 for p in coll.get_paths()]
                    coll.set_linewidths(widths)
                
                for coll in cg.ax_col_dendrogram.collections:
                    widths = [4.5 if np.any(np.isclose(p.vertices[:, 1], 0, atol=1e-3)) else 3.0 for p in coll.get_paths()]
                    coll.set_linewidths(widths)
                
                # Title and labels (Y-axis label removed as requested)
                cg.fig.suptitle('2D HEATMAP', fontsize=18, fontweight='bold', y=1.05)
                cg.ax_heatmap.set_xlabel("Hierarchical Clustering of Shared GO Terms (Jaccard distance) [CC brown, BP yellow, MF green]", fontsize=12, fontweight='bold', labelpad=20)
                cg.ax_heatmap.set_ylabel("")
                
                plt.setp(cg.ax_heatmap.get_yticklabels(), rotation=0)
                plt.setp(cg.ax_heatmap.get_xticklabels(), rotation=45, ha='right', fontsize=10)
                
                for tick in cg.ax_heatmap.get_xticklabels():
                    label_text = tick.get_text()
                    go_id = label_text.split(" - ")[0]
                    ns = str(term_to_ns.get(go_id, '')).lower()
                    
                    if 'cellular' in ns or 'cc' in ns:
                        tick.set_color('saddlebrown')
                        tick.set_fontweight('bold')
                    elif 'biological' in ns or 'bp' in ns:
                        tick.set_color('goldenrod') 
                        tick.set_fontweight('bold')
                    elif 'molecular' in ns or 'mf' in ns:
                        tick.set_color('forestgreen')
                        tick.set_fontweight('bold')
                
                heatmap_out = f"{prefix}2D-Heatmap.pdf"
                cg.savefig(heatmap_out, bbox_inches='tight')
                plt.close()
                
                print(f" -> Success! Generated '{heatmap_out}'")
            else:
                print(f" -> Not enough valid records (Prec<={max_prec}) to build a 2D Heatmap.")
                
        except Exception as e:
            print(f"Warning: Failed to generate 2D Heatmap: {e}")
    else:
        print(f"Note: '{sig_prots_file}' not found. Skipping 2D Heatmap generation.")

    # List to store figures for the Comparison PDF
    comparison_figs = []

    # -------------------------------------------------------------------------
    # 6. ADDED TERMS BAR CHART (Parents vs Children relative to Prec=1)
    # -------------------------------------------------------------------------
    if not sp_df_filtered.empty and max_prec > 1:
        print("Generating Bar Chart of relative added terms (Parents vs Children)...")
        try:
            terms_p1 = set(sp_df_filtered[sp_df_filtered['Prec_Num'] == 1]['GOTerm'])
            
            if len(terms_p1) > 0:
                prec_levels = []
                parent_counts = []
                child_counts = []
                
                for p in range(2, max_prec + 1):
                    terms_leq_p = set(sp_df_filtered[(sp_df_filtered['Prec_Num'] > 1) & (sp_df_filtered['Prec_Num'] <= p)]['GOTerm'])
                    
                    is_parent_to_p1 = edges_df[(edges_df['Child'].isin(terms_p1)) & (edges_df['Parent'].isin(terms_leq_p))]
                    num_parents = is_parent_to_p1['Parent'].nunique()
                    
                    is_child_to_p1 = edges_df[(edges_df['Parent'].isin(terms_p1)) & (edges_df['Child'].isin(terms_leq_p))]
                    num_children = is_child_to_p1['Child'].nunique()
                    
                    prec_levels.append(f"≤ {p}")
                    parent_counts.append(num_parents)
                    child_counts.append(num_children)
                
                x = np.arange(len(prec_levels))
                width = 0.35
                
                fig, ax = plt.subplots(figsize=(8, 6))
                fig.suptitle('COMPARISON GRAPHS', fontsize=16, fontweight='bold')
                
                rects1 = ax.bar(x - width/2, parent_counts, width, label='Added as Parents to Prec=1', color='indianred')
                rects2 = ax.bar(x + width/2, child_counts, width, label='Added as Children to Prec=1', color='steelblue')
                
                ax.set_ylabel('Count of Added GO Terms', fontsize=12)
                ax.set_title('Functional Relationship of Added Terms relative to Precedence=1 Core', fontsize=14, pad=15)
                ax.set_xticks(x)
                ax.set_xticklabels(prec_levels, fontsize=12)
                ax.legend(fontsize=11)
                
                ax.bar_label(rects1, padding=3, fontsize=11)
                ax.bar_label(rects2, padding=3, fontsize=11)
                
                fig.tight_layout()
                
                comparison_figs.append(fig)
                print(" -> Success! Bar chart generated and stored for Comparison PDF.")
            else:
                print(" -> Notice: No Precedence=1 terms found to act as a comparative core. Skipping Bar Chart.")
        except Exception as e:
            print(f"Warning: Failed to generate Added Terms Bar Chart: {e}")

    # -------------------------------------------------------------------------
    # 7. OVERLAP VENN DIAGRAM & SUMMARY TABLE
    # -------------------------------------------------------------------------
    has_slim_terms = any(sig_results['Is_Slim'].astype(str).str.strip().str.lower() == 'yes')
    has_high_terms = len(highlighted_terms) > 0

    if has_slim_terms or has_high_terms:
        print("Generating Overlap Venn Diagram and Summary Table...")
        try:
            from matplotlib_venn import venn2, venn3
            import matplotlib.colors as mc

            sig_results['neg_log_P'] = -np.log10(pd.to_numeric(sig_results['P_Value'], errors='coerce'))

            total_terms = set(sig_results['GOTerm'])
            total_count = len(total_terms)

            set_prec1 = set(sig_results[sig_results['Prec_Num'] == 1]['GOTerm'])
            set_slim = set(sig_results[sig_results['Is_Slim'].astype(str).str.strip().str.lower() == 'yes']['GOTerm'])
            set_high = set(sig_results[sig_results['GOTerm'].isin(highlighted_terms)]['GOTerm'])

            sets_to_plot = [set_prec1]
            set_labels = ['Precedence=1']
            table_data = []

            def get_set_stats(term_set, name):
                pct = (len(term_set) / total_count * 100) if total_count > 0 else 0
                avg_p = sig_results[sig_results['GOTerm'].isin(term_set)]['neg_log_P'].mean()
                return [name, f"{pct:.1f}%", f"{avg_p:.2f}"]

            table_data.append(get_set_stats(set_prec1, 'Precedence=1'))

            if has_slim_terms:
                sets_to_plot.append(set_slim)
                set_labels.append('GOSlims')
                table_data.append(get_set_stats(set_slim, 'GOSlims'))

            if has_high_terms:
                sets_to_plot.append(set_high)
                high_name = os.path.basename(highlight_file) if highlight_file else "Highlights"
                set_labels.append(high_name)
                table_data.append(get_set_stats(set_high, high_name))

            # Only append title if it's the first comparison graph
            fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 10), gridspec_kw={'height_ratios': [2, 1]})
            if len(comparison_figs) == 0:
                fig.suptitle('COMPARISON GRAPHS', fontsize=16, fontweight='bold')

            colors2 = ['#ff9999', '#99cc99']
            colors3 = ['#ff9999', '#99cc99', '#9999ff']

            if len(sets_to_plot) == 2:
                v = venn2(sets_to_plot, set_labels=set_labels, set_colors=colors2, ax=ax1)
                row_colors = colors2
            else:
                v = venn3(sets_to_plot, set_labels=set_labels, set_colors=colors3, ax=ax1)
                row_colors = colors3

            ax1.set_title("Overlap of Significant GO Terms", fontsize=14, pad=15)

            ax2.axis('tight')
            ax2.axis('off')
            
            col_labels = [
                "Set Name", 
                "% Coverage\n(of the significant terms)", 
                "Average\n-log10(P-value)"
            ]
            
            table = ax2.table(
                cellText=table_data, 
                colLabels=col_labels, 
                cellLoc='center', 
                loc='center'
            )
            
            table.auto_set_font_size(False)
            table.set_fontsize(11)
            table.scale(1, 2.5)

            for i in range(len(table_data)):
                rgba = mc.to_rgba(row_colors[i], alpha=0.3)
                table[(i+1, 0)].set_facecolor(rgba)
                table[(i+1, 0)].set_text_props(weight='bold')

            for j in range(3):
                table[(0, j)].set_facecolor('#d3d3d3')
                table[(0, j)].set_text_props(weight='bold')

            fig.tight_layout()
            
            comparison_figs.append(fig)
            print(" -> Success! Venn diagram and colored Summary Table generated and stored for Comparison PDF.")

        except ImportError:
            print(" -> Error: The 'matplotlib-venn' library is not installed. Please run 'pip install matplotlib-venn' to generate the Venn diagram.")
        except Exception as e:
            print(f"Warning: Failed to generate Venn Diagram and Table: {e}")

    # -------------------------------------------------------------------------
    # 8. EXPORT COMBINED COMPARISON PDF
    # -------------------------------------------------------------------------
    if comparison_figs:
        comp_out = f"{prefix}Comparison-Graphs.pdf"
        with PdfPages(comp_out) as pdf:
            for f in comparison_figs:
                pdf.savefig(f, bbox_inches='tight')
                plt.close(f)
        print(f"\n -> Final Success! Combined all auxiliary plots into '{comp_out}'.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Draw Precedence Graphs from GOParsimony C Parser Output")
    
    parser.add_argument("--results", required=True, help="Path to Enrichment_Results.tsv file")
    parser.add_argument("--edges", required=True, help="Path to Precedence_Edges.tsv file")
    parser.add_argument("--out", default="", help="Output file prefix (optional)")
    parser.add_argument("--highlight", help="Path to a text file containing GO terms to highlight with a green border")
    
    # Updated default name in the help description
    parser.add_argument("--sig_prots", help="Path to Significantly_Annotated_List.tsv file (auto-detected if not provided)")
    
    parser.add_argument("--max_prec", type=int, default=5, help="Maximum precedence threshold to include in clustering (default: 5)")
    
    args = parser.parse_args()
    
    generate_graphs(args.results, args.edges, args.out, args.highlight, args.sig_prots, args.max_prec)



